# CSI Driver NFS — Build and push to GHCR
# Triggers on tag push (v*) or manual run
when:
  - event: tag
    ref: refs/tags/v*
  - event: manual

steps:
  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx:6.1.1@sha256:9a22c00b4952e405d11e66d29772edbeb1f7b24f27f71cda251ecb838e725e86
    privileged: true
    settings:
      registry: ghcr.io
      repo: ghcr.io/isityael/nfsplugin
      dockerfile: Dockerfile.release
      build_args:
        IMAGE_VERSION: "${CI_COMMIT_TAG}"
        GIT_COMMIT: "${CI_COMMIT_SHA}"
        GO_VERSION: "1.27.1@sha256:f773aa2679c165b2d4ccf04c1de9ef5f34c0e4fd7008b3c449d4cdc47d83af55"
      platforms:
        - linux/amd64
      tags:
        - "${CI_COMMIT_TAG##v}"
        - "${CI_COMMIT_TAG}"
        - latest
      logins:
        - registry: ghcr.io
          username:
            from_secret: github_username
          password:
            from_secret: github_token
        - registry: dhi.io
          username:
            from_secret: dhi_username
          password:
            from_secret: dhi_password
      provenance: mode=max
      buildkit_driveropt: network=host
      cache_from: 'type=registry\,ref=ghcr.io/isityael/nfsplugin:buildcache'
      cache_to: "type=registry,ref=ghcr.io/isityael/nfsplugin:buildcache,mode=max,ignore-error=true"

  - name: trivy-scan
    failure: ignore
    image: dhi.io/trivy:0.74.0-alpine3.23-dev@sha256:ba121066eda82f3780b4825196f97f471eb63f4516eccc76aa8f06f116e59a19
    environment:
      IMAGE_REF: "ghcr.io/isityael/nfsplugin:${CI_COMMIT_TAG}"
      TRIVY_USERNAME:
        from_secret: github_username
      TRIVY_PASSWORD:
        from_secret: github_token
    commands:
      - trivy image --exit-code 1 --severity CRITICAL --ignore-unfixed $${IMAGE_REF}
      - trivy image --exit-code 0 --severity HIGH --ignore-unfixed $${IMAGE_REF}

  - name: cosign-sign
    image: dhi.io/cosign:3.1.3-alpine3.23-dev@sha256:8eb37c22adda233a7bd6c1e49beb21cacc5dc11edb6e1a7c88b971699f29f986
    environment:
      IMAGE_REF: "ghcr.io/isityael/nfsplugin:${CI_COMMIT_TAG}"
      COSIGN_EXPERIMENTAL: "1"
      COSIGN_KEY:
        from_secret: cosign_key
      COSIGN_PASSWORD:
        from_secret: cosign_password
      REGISTRY_USERNAME:
        from_secret: github_username
      REGISTRY_PASSWORD:
        from_secret: github_token
    commands:
      - echo "$COSIGN_KEY" > /tmp/cosign.key
      - cosign login ghcr.io -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
      - cosign sign --key /tmp/cosign.key --yes --registry-referrers-mode=oci-1-1 $${IMAGE_REF}
      - rm -f /tmp/cosign.key
