# CSI Driver NFS — Build and push to GHCR
# Triggers on tag push (v*) or manual run
when:
  - event: tag
    ref: refs/tags/v*
  - event: manual

steps:
  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx:6.1.1@sha256:9a22c00b4952e405d11e66d29772edbeb1f7b24f27f71cda251ecb838e725e86
    privileged: true
    settings:
      registry: ghcr.io
      repo: ghcr.io/isityael/nfsplugin
      dockerfile: Dockerfile.release
      build_args:
        IMAGE_VERSION: "${CI_COMMIT_TAG}"
        GIT_COMMIT: "${CI_COMMIT_SHA}"
        GO_VERSION: "1.26.5@sha256:3aff6657219a4d9c14e27fb1d8976c49c29fddb70ba835014f477e1c70636647"
      platforms:
        - linux/amd64
      tags:
        - "${CI_COMMIT_TAG##v}"
        - "${CI_COMMIT_TAG}"
        - latest
      logins:
        - registry: ghcr.io
          username:
            from_secret: github_username
          password:
            from_secret: github_token
        - registry: dhi.io
          username:
            from_secret: dhi_username
          password:
            from_secret: dhi_password
      provenance: mode=max
      buildkit_driveropt: network=host
      cache_from: 'type=registry\,ref=ghcr.io/isityael/nfsplugin:buildcache'
      cache_to: "type=registry,ref=ghcr.io/isityael/nfsplugin:buildcache,mode=max,ignore-error=true"

  - name: trivy-scan
    failure: ignore
    image: dhi.io/trivy:0.71.2-alpine3.23-dev@sha256:6d812147979905c7cc90bbb3d2fc0bb04450f3ac4d6bb3447fad53ce709a4b21
    environment:
      IMAGE_REF: "ghcr.io/isityael/nfsplugin:${CI_COMMIT_TAG}"
      TRIVY_USERNAME:
        from_secret: github_username
      TRIVY_PASSWORD:
        from_secret: github_token
    commands:
      - trivy image --exit-code 1 --severity CRITICAL --ignore-unfixed $${IMAGE_REF}
      - trivy image --exit-code 0 --severity HIGH --ignore-unfixed $${IMAGE_REF}

  - name: cosign-sign
    image: dhi.io/cosign:3.1.2-alpine3.23-dev@sha256:ae1c995e4df642e20c81b258dadefa4d5bb9e3cf08d6a2f3f958b525367bc0e8
    environment:
      IMAGE_REF: "ghcr.io/isityael/nfsplugin:${CI_COMMIT_TAG}"
      COSIGN_EXPERIMENTAL: "1"
      COSIGN_KEY:
        from_secret: cosign_key
      COSIGN_PASSWORD:
        from_secret: cosign_password
      REGISTRY_USERNAME:
        from_secret: github_username
      REGISTRY_PASSWORD:
        from_secret: github_token
    commands:
      - echo "$COSIGN_KEY" > /tmp/cosign.key
      - cosign login ghcr.io -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
      - cosign sign --key /tmp/cosign.key --yes --registry-referrers-mode=oci-1-1 $${IMAGE_REF}
      - rm -f /tmp/cosign.key
